name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create public directory
        run: mkdir -p public


      - name: Generate index.html
        run: |
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Fluid Simulation Projects</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background: #0a0a0a;
                      color: #00ff88;
                  }
                  h1 {
                      text-align: center;
                      color: #ff0088;
                      text-shadow: 0 0 10px #ff0088;
                  }
                  .file-list {
                      list-style: none;
                      padding: 0;
                  }
                  .file-item {
                      margin: 10px 0;
                      padding: 15px;
                      background: linear-gradient(45deg, #001122, #002244);
                      border: 1px solid #00ff88;
                      border-radius: 5px;
                      transition: all 0.3s ease;
                  }
                  .file-item:hover {
                      border-color: #ff0088;
                      box-shadow: 0 0 15px rgba(255, 0, 136, 0.5);
                  }
                  .file-link {
                      color: #00ff88;
                      text-decoration: none;
                      font-size: 18px;
                      display: block;
                  }
                  .file-link:hover {
                      color: #ff0088;
                  }
              </style>
          </head>
          <body>
              <h1>🌊 Fluid Simulation Projects</h1>
              <ul class="file-list">
          EOF

          # Find HTML files and generate links
          find public -name "*.html" -not -name "index.html" | sort | while read file; do
              filename=$(basename "$file")
              filepath=${file#public/}
              echo "                  <li class=\"file-item\">" >> public/index.html
              echo "                      <a href=\"$filepath\" class=\"file-link\">$filename</a>" >> public/index.html
              echo "                  </li>" >> public/index.html
          done

          cat >> public/index.html << 'EOF'
              </ul>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4